apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: aws-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-example 
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: app 
          image: "hashicorp/vault-example-aws:0.0.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: "http://10.0.2.2:8200"
